---
apiVersion: "v1"
kind: "Service"
metadata:
  annotations:
    fabric8.io/iconUrl: "img/icons/spring-boot.svg"
    fabric8.io/git-commit: "9f6eed80a6ca102ea8077b50311d39be20efda98"
    fabric8.io/git-branch: "master"
  labels:
    provider: "fabric8"
    project: "demo"
    version: "0.0.1-SNAPSHOT"
    group: "com.example"
  name: "demo"
spec:
  ports:
  - port: 8080
    protocol: "TCP"
    targetPort: 8080
  selector:
    project: "demo"
    provider: "fabric8"
    group: "com.example"
  type: "LoadBalancer"
