---
apiVersion: "v1"
kind: "List"
items:
- apiVersion: "v1"
  kind: "Service"
  metadata:
    annotations:
      fabric8.io/iconUrl: "img/icons/spring-boot.svg"
      fabric8.io/git-commit: "9f6eed80a6ca102ea8077b50311d39be20efda98"
      fabric8.io/git-branch: "master"
    labels:
      provider: "fabric8"
      project: "demo"
      version: "0.0.1-SNAPSHOT"
      group: "com.example"
    name: "demo"
  spec:
    ports:
    - port: 8080
      protocol: "TCP"
      targetPort: 8080
    selector:
      project: "demo"
      provider: "fabric8"
      group: "com.example"
    type: "LoadBalancer"
- apiVersion: "v1"
  kind: "DeploymentConfig"
  metadata:
    annotations:
      fabric8.io/iconUrl: "img/icons/spring-boot.svg"
      fabric8.io/git-commit: "9f6eed80a6ca102ea8077b50311d39be20efda98"
      fabric8.io/metrics-path: "dashboard/file/kubernetes-pods.json/?var-project=demo&var-version=0.0.1-SNAPSHOT"
      fabric8.io/git-branch: "master"
    labels:
      provider: "fabric8"
      project: "demo"
      version: "0.0.1-SNAPSHOT"
      group: "com.example"
    name: "demo"
  spec:
    replicas: 1
    selector:
      project: "demo"
      provider: "fabric8"
      group: "com.example"
    strategy:
      rollingParams:
        timeoutSeconds: 10800
      type: "Rolling"
    template:
      metadata:
        annotations:
          fabric8.io/iconUrl: "img/icons/spring-boot.svg"
          fabric8.io/git-commit: "9f6eed80a6ca102ea8077b50311d39be20efda98"
          fabric8.io/metrics-path: "dashboard/file/kubernetes-pods.json/?var-project=demo&var-version=0.0.1-SNAPSHOT"
          fabric8.io/git-branch: "master"
        labels:
          provider: "fabric8"
          project: "demo"
          version: "0.0.1-SNAPSHOT"
          group: "com.example"
      spec:
        containers:
        - env:
          - name: "KUBERNETES_NAMESPACE"
            valueFrom:
              fieldRef:
                fieldPath: "metadata.namespace"
          image: "example/demo:snapshot-180223-092953-0905"
          imagePullPolicy: "IfNotPresent"
          livenessProbe:
            httpGet:
              path: "/health"
              port: 8080
            initialDelaySeconds: 180
          name: "spring-boot"
          ports:
          - containerPort: 8080
            protocol: "TCP"
          - containerPort: 9779
            protocol: "TCP"
          - containerPort: 8778
            protocol: "TCP"
          readinessProbe:
            httpGet:
              path: "/health"
              port: 8080
            initialDelaySeconds: 10
          securityContext:
            privileged: false
    triggers:
    - type: "ConfigChange"
